# Generated by Django 4.2 on 2023-07-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_description',
            field=models.TextField(default=''),
        ),
    ]
