# Generated by Django 4.2.4 on 2023-08-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponapp', '0002_coupon_coupon_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='', upload_to='category/images'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
