# Generated by Django 4.2.4 on 2023-09-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponapp', '0003_category_category_image_category_slug_store_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='store_logo',
            field=models.ImageField(default='', upload_to='coupon/images'),
        ),
    ]
