# Generated by Django 4.2.4 on 2023-09-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couponapp', '0004_coupon_store_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='store_logo',
        ),
    ]
